apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi
          image: 429722559165.dkr.ecr.ap-southeast-1.amazonaws.com/fastapi-app:17-4e3c0fd
          ports:
            - containerPort: 8000
